{"a10-networks": ["Makes high-performance server appliances designed to help organizations of all sizes with security, speed, and performance. A10 Networks develops server load-balancing hardware especially for enterprise application delivery, carrier and Internet service providers, and cloud computing and virtualization entities."]}
{"acquia": ["Provides products, services, and technical support for the open source Drupal social publishing system for organizations such as Al Jazeera, Stanford University, and Twitter."]}
{"acquirent": ["Provides outsourced sales for midsize companies as well as major corporations. Acquirent hires, trains, and manages sales teams to be a part of clients' sales infrastructure or their entire sales force."]}
{"acquity-group": ["Offers digital marketing services in strategy, design, and technology to create unique experiences to build its clients' customer relationships. Customers include the New York Philharmonic and American Airlines."]}
{"acronis": ["Develops disaster recovery, backup, and IT security software used by corporations, small and midsize businesses, and consumers to protect their digital information, maintain business continuity, and reduce downtime. Its products are sold in more than 90 countries and are available in 14 languages."]}
{"aegis-mobile": ["Provides compliance services for companies, insuring that their online presenceboth PC and mobilecomplies with their own policies as well as with applicable regulations and industry guidelines. Aegis Mobile also offers mobile strategy consulting, e-commerce site development, and systems integration of mobile applications."]}
{"agosto": ["Agosto provides managed services, technology resources, software development, and strategy services to small and midsize businesses."]}
{"ahead": ["Specializes in data center networking, enterprise storage deployment, server virtualization and management, and end-user and application virtualization services."]}
{"airnet-group": ["Provides Internet connectivity, disaster recovery, colocation, VoIP, audio and video streaming, Web hosting, and broadcast e-mail services."]}
{"ajax-union": ["A boutique Internet marketing firm that develops and implements strategies to enhance the online presence of its small and midsize business clients and help them outrank their larger competitors."]}
{"all-star-directories": ["All Star Directories sells online recruitment tools used by research and educational institutions to match prospective students with the schools that best meet their education needs."]}
{"allegiance": ["Allegiance provides Voice-of-the-Customer (VOC) and Enterprise Feedback Management (EFM) services for organizations. The Allegiance Engage platform is a feedback system that collects and analyzes the voices of customers and employees through multiple channels (email, Web, print, phone) into a central database for analysis and action."]}
{"altitude-digital-partners": ["A full-service ad rep firm that works with publishers to navigate online advertising while maximizing online revenue. It offers publishers competitive cost per impression rates for display and video content."]}
{"andera": ["Develops Web-based account opening and funding software that automates the customer acquisition process throughout a financial institution's various delivery channels, including branches, call centers, and Web sites."]}
{"animax-entertainment": ["Animax Entertainment is a digital agency that produces multiplatform original and branded entertainment. Pioneering the realm of transmedia and creative technology, Animax produces animated and live-action video for TV and online, games, virtual worlds and MMOs (massively multiplayer online games), mobile apps and other social media. The company was founded by Emmy-winning writer, producer, and actor Dave Thomas (of SCTV fame) and Andrew Bain, a founder of multiple ad agencies and technology firms."]}
{"answerlab": ["Conducts custom user-experience research to improve websites, software, and mobile applications.Its customers include Amazon.com, PayPal, Honda, ING DIRECT, ESPN, FedEx, Genentech, eBay, Salesforce.com, Amgen, Intuit and Harley Davidson."]}
{"anue-systems": ["Anue Systems makes and sells devices that allow businesses to test, secure, and monitor their networked applications. Anue Systems also offers its customers, which include HP, Lockheed Martin, and Shell Oil, a wide variety of data monitoring, network and storage equipment testing, and disaster recovery services."]}
{"appliedtrust": ["Provides IT consulting services focused on the security, performance, and availability of system and network infrastructure for businesses in high technology, energy, utilities, financial services, education, government, and health care."]}
{"appriver": ["Offers a comprehensive subscription-based software-as-a-service that incorporates spam and virus protection, e-mail encryption, and Web security features."]}
{"aprimo": ["Aprimo creates marketing software such as Aprimo Marketing Studio B2C and Aprimo Marketing Studio B2B and provides services for marketing organizations."]}
{"arteris": ["Provides network-on-chip (NoC) interconnect semiconductor intellectual property to improve performance, power consumption, and die size of system-on-chip (SoC) devices for consumer electronics, mobile, automotive, and other applications."]}
{"arvixe": ["Hosts thousands of personal, small business, and enterprise websites."]}
{"arxan-technologies": ["Helps customers stop software piracy."]}
{"ascentium": ["Ascentium is a digital advertising company with expertise in brand strategy, Web design and development, customer relationship management (CRM), and business intelligence. Customers include Dell, T-Mobile, and Random House"]}
{"aspen-marketing-services": ["Provides marketing services, integrating traditional marketing with digital and emerging channels."]}
{"astaro": ["Astaro\u00e2\u20ac\u2122s software solutions help companies protect their networks from data theft, viruses, spyware and spam."]}
{"astonish-results": ["Provides Web development and marketing services to help insurance agencies grow their internal business and generate leads through the tactical use of e-mail marketing, customer relationship management (CRM), social media construction and strategy, and search engine marketing (SEM). Astonish represents more than 700 insurance agencies from nearly every state."]}
{"atlantic-bt": ["Offers Web design, custom scripting, Web hosting, Internet marketing, and copy services to local, national, and international clients."]}
{"atlantic-metro-communications": ["Utilizes a cloud computing technology platform and nationwide network to offer a comprehensive suite of customizable managed services."]}
{"attask": ["Develops project and portfolio management software that increases efficiency for businesses of all sizes."]}
{"avalara": ["Develops Web-based sales tax automation software."]}
{"avepoint": ["Offers comprehensive and flexible infrastructure support for SharePoint data protection, replication, migration, administration, content lifecycle management, storage optimization, deployment management, compliance, and SharePoint-Salesforce.com integration."]}
{"axcient": ["Offers a unified platform for protection of businesses' data that ensures backup, business continuity, and disaster recovery. The cloud-based service requires no infrastructure, license, or software costs, thereby eliminating capital expenditures and minimizing operating expenses."]}
{"azavea": ["Azavea, formerly Avencia, develops custom software for mapping and geographic analysis used by commercial, government, and educational clients."]}
{"balihoo": ["Offers Web-based marketing automation software and services to national brands with local marketing needs, enabling them to dramatically reduce their marketing expenses and immediately increase local sales revenue."]}
{"bancvue": ["Provides innovative products, marketing, and data-driven consulting to to community financial institutions across the U.S. Its continued growth during the worst financial crisis since the Great Depression reflects the success of its battle against the megabanks. Over the last year, BancVue has adjusted to changing regulations and shifting consumer sentiment through ongoing research, new product development, and continuous refinement of existing products."]}
{"bandwidth-com": []}
{"bayru": ["Operates a cross-border shopping site that sells products from the United States to consumers in Russia and the Commonwealth of Independent States."]}
{"bazaarvoice": ["Provides social commerce software that helps clients capture, display, and analyze online word of mouth, including consumer-generated ratings and reviews, questions and answers, stories, recommendations, photographs, videos and other content about their brands, products, and services."]}
{"berkeley-bionics": ["Designs wearable, artificially intelligent bionic exoskeletons that help paralyzed people walk again. The robotic devices are tethered to the user, powered, and provide a natural human gait. Its eLEGS device was named by Time Magazine as one of the 50 best inventions of 2010."]}
{"big-fish-games": ["Big Fish Games develops casual games and publishes them online."]}
{"big-nerd-ranch": ["Develops mobile applications and trains programmers in the company's mobile strategy. Works with some of the biggest companies in the world including Apple. Known for best-selling, how-to guides for nerds, Big Nerd Ranch applies a monastic retreat approach to training classes at the Ranch."]}
{"bigcommerce": ["BigCommerce, formely Interspire, is the leading SaaS e-commerce shopping cart software. It has been chosen by well over 23,000 successful businesses looking to grow their businesses and revenues using the reach and affordability of e-commerce."]}
{"bizo": ["Specializes in reaching and engaging business professionals wherever they travel online. It can precisely target more than 100 million professionals around the world, including more than 80 percent of the U.S. business population, enabling it to give clients like Monster and FedEx precise display ad targeting, social media measurement, and deep audience analytics."]}
{"blackline": []}
{"blue-fountain-media": ["A full-service digital agency that offers Web design and development, online marketing, and online business strategy consulting services. Other services include branding, application development, online reputation management, and copywriting. CEO Gabriel Shaoolian authors the \"Site Analysis\" column in the New York Times."]}
{"bmi-gaming": ["Sells arcade games, pinball machines, air hockey tables, jukeboxes, photo booths, and similar amusements to businesses and homeowners."]}
{"boomtown": ["A Web-based software company specializing in a marketing system for real estate professionals. The platform includes a customized real estate website integrated with local MLS (multiple listing service) data, personalized online advertising campaigns, and a leads management system with marketing automation tools."]}
{"boston-technologies": ["Specializes in foreign exchange (FX) trading technology, software, support, transaction processing services, and liquidity access for FX retail brokers, institutional traders, small to medium size hedge funds, and other institutional FX market participants."]}
{"boundless-network": ["Provides branded promotional products and services, including technology to manage promotional spending. GroupBuy is a Web-based application that allows multiple buyers in various locations to purchase a product as a buying group, allowing for bulk discounts."]}
{"boxtone": ["Sells software designed to manage, monitor, and support mobile applications for BlackBerry, iPhone, iPad, Android, and Windows Mobile devices. Its clients include managed service providers, large companies, and government agencies."]}
{"brafton": ["Provides full-spectrum content marketing services to increase brand authority, website traffic and leads. Brafton's custom content, from news and blogs to infographics and video, is supported by SEO consultancy, social strategies and defined conversion metrics."]}
{"brickhouse-security": ["BrickHouse Security provides security, safety, and surveillance products from locks, cameras, and baby monitors to tracking devices, night vision goggles, stun guns, and spy gear. Its customers are consumers, businesses of all sizes, and government agencies such as the NYPD, the Los Angeles County Sheriff's Department, and the FBI."]}
{"brightbox": ["Provides brand marketing to nearly every industry, from start-ups to corporations. It offers strategic marketing, PR, Web design and development, 3D animation and illustration, video and motion graphics, print design and production, and event management."]}
{"brightcove": ["Provides cloud-based services for publishing and distributing professional digital media. Customers include the New York Times and General Motors."]}
{"broadsoft": ["BroadSoft develops VoIP application software that enables the delivery of hosted telephony and multimedia services to eight of the top 10 and 14 of the top 25 largest carriers worldwide."]}
{"bronto-software": ["Provides a marketing platform for retailers and other commerce-focused companies to increase revenue through e-mail, mobile, and social campaigns. Its more than 1,000 customers include Trek and CoffeeForLess.com"]}
{"buddytv": ["A TV and entertainment website that provides recaps, photos, games, and information about shows like Glee, American Idol, and The Bachelorette. Its mobile apps help viewers quickly find what they want to watch, with a preferred channel guide based on their viewing history, as well as reveals what their friends are watching."]}
{"buildium": ["Develops and licenses online property management software with editions designed for private landlords, property management firms, homeowners associations and condominiums. This web-based software as a service allows landowners, residents and property managers worldwide to complete tenant applications, track expenses and submit payments over the Internet."]}
{"business-insider": ["A business news website that publishes continuous real-time news, analysis, and original commentary. Business Insider was founded by Henry Blodget, the financial journalist and former Wall Street analyst, and two former executives of DoubleClick."]}
{"call-em-all": ["Provides on-demand automated voice broadcasting and text messaging technology for large and small corporate clients."]}
{"carpathia-hosting": ["Provides secure, reliable, and compliant IT infrastructure and managed hosting services for a range of industries."]}
{"central-desktop": ["Central Desktop provides a software-as-a-service (SaaS) social technology platform designed to allow business teams to interact, share, and manage their daily work activities. Central Desktop offers a comprehensive suite of online collaboration tools including wikis, file sharing, task management, web conferencing, online spreadsheets, shared calendars and micro-blogging."]}
{"centro": ["Provides media logistics software (its proprietary Transis) and digital media campaign services for ad agencies, publishers, and advertisers."]}
{"cfn-services": ["Provides telecommunications network deployment to the largest US carriers including AT&T, Verizon, Level 3 and Sprint. The company specializes in network design, planning, deployment, and managed services."]}
{"chacha": ["Delivers real-time, human-powered answers, free-of-charge, to any question asked via the Internet, telephone, text, or mobile apps. It has answered a billion questions to date. The interactive site offers brand advertisers such as Coca-Cola and Paramount a way to engage with their target audiences."]}
{"christmas-lights-etc": ["Internet retailer of holiday lighting and decorations."]}
{"ciplex": ["Provides creative, technology, and marketing services."]}
{"clarity": ["Clarity is a North-American surface freight forwarding company, specializing in mid-market manufacturing and distribution companies."]}
{"clevertech": ["Develops customized software applications for startup companies and enterprises that are restructuring operations."]}
{"clinipace-worldwide": ["Specializes in clinical research services for phase I-IV trials and registries for biopharmaceutical and medical device firms. The company has particular expertise in oncology."]}
{"collaboratemd": ["Offers cloud-based medical practice and billing management services that enable 5,000 medical providers to more efficiently manage their offices and collect their accounts receivable."]}
{"comverge": ["Provides IT services like copper and fiber-optic cabling and computer network support and deployment. Also includes telecommunication services such as Internet access, and voice and data networks."]}
{"conductor": ["Conductor provides SEO measurement and optimization tools. Conductor Searchlight is a subscription-based, software as a service (SaaS) platform designed to allow its customers to gather competitive data, prioritize and improve their decision making, and accurately measure the ROI of their SEO efforts. Conductor's customers include major corporations, Internet retailers, interactive agencies, and publications."]}
{"confio-software": ["Develops database performance tools for database administrators, IT managers, and database developers, operating in both physical and virtual server environments. Sells software designed to reduce bottlenecks, expedite problem resolution, and lower operating costs for databases including SQL Server, DB2, Oracle, and Sybase as well as VMware servers."]}
{"conigent": ["Helps clients select and implement appropriate enterprise resource planning systems, customer relationship management systems and transportation management tools. Also develops public and private cloud-based applications."]}
{"constant-contact": ["Helps small businesses and non-profits manage and monitor their customer relationships with online and e-mail-based surveys and newsletters."]}
{"consumer-united": ["A venture capital-backed company that operates a free-membership website for consumers that helps them find the best rates and coverage on auto, home, and life insurance and cell phone plans."]}
{"contact-at-once": ["Operates industry-specific merchant networks built around its proprietary website chat software embedded in online ads on landing pages. Its chat tools typically increase by 25 percent the number of online shoppers who initiate contact with its real estate and automotive clients on their websites."]}
{"convert2media": ["A performance-based affiliate network and lead generation company."]}
{"convio-2": []}
{"couponcabin": ["CouponCabin.com is an online database of coupons that can be used exclusively for Internet purchases."]}
{"cpower": ["CPower offers energy management services that enable companies to optimize their facilities and operations through strategic energy reduction initiatives, including programs that monetize their reduction efforts."]}
{"cprime": ["Offers project management consulting, staffing, and training, with a growing concentration in enterprise agile adoptions."]}
{"cpx-interactive": ["CPX Interactive operates an online display advertising network of thousands of member websites; clients choose from different advertising packages depending on the marketing reach and target refinement they want."]}
{"creative-solutions-services": ["Provides high volume executive search, temporary and temp-to-hire staffing services, MSP recruiting services, workforce compliance, and payroll services nationwide."]}
{"credant-technologies": ["Credant Technologies provides endpoint security against internal and external data breaches."]}
{"credit-karma": ["Offers free access and ongoing tracking of consumers' credit scores, as well as credit simulators, credit advice, and access to special offers from companies that value consumer creditworthiness."]}
{"curse": ["A site for gaming content and community that offers editorial features, video, databases, wikis, forums, add-ons, and a desktop applications that helps gamers find and install gaming plug-ins."]}
{"customink": ["CustomInk sells t-shirts and athletic apparel, as well as gift items such as holiday ornaments and golf balls, that customers (student groups, bands, small businesses) can customize using its online design lab. The founders are three college friends who say the company attracts employees with \"heart\"--the ones who get a bad feeling in the pit of their stomachs if they think they're going to let someone down and repels those who don't. CustomInk.com streams all of its customer feedback, completely uncensored and unedited, on its home page."]}
{"cybera": ["Provides security services including remote, cloud-based and multi-site. Cyberia offers network services, including VPN, back-up connectivity, 3G, and 4G for businesses in the retail and restaurant industries."]}
{"cyrus-innovation": ["Provides agile software (extreme programming and scrum) coaching and development services."]}
{"datacert": ["Provides spend management software and services to corporate legal departments."]}
{"dataprise": ["Offers a range of information technology services to businesses in Washington DC, Maryland, Virginia, Philadelphia, New York City and New Jersey. Services are designed to provide a completely outsourced IT department, including managed services, network installation and integration, computer repair, help desk, data backup, and consulting on special projects."]}
{"datto": ["Provides hardware-based on-site and offsite backup, disaster recovery, and business continuity services for municipalities, small businesses, and organizations in education, health care, retail, law, and financial services."]}
{"dean-evans-associates": ["Makes software used for room scheduling, meeting management, Web calendaring, online event registration, and surveys."]}
{"delivra": ["Provides software that makes it easy for companies to manage their e-mail marketing campaigns, with features like list management and segmentation, personalization, tracking and reporting, and WYSIWYG editing, and also offers professional production and design services."]}
{"demandforce": ["Provides a software-as-a-service application, D3, that connects its clients to consumers via E-mail, text messaging and online services. D3 guarantees revenue generation, improved customer activity, satisfaction, and retention, and new customer recruitment."]}
{"deviceanywhere": ["DeviceAnywhere helps companies test and develop applications for mobile phones through an online portal. Its Web application allows clients to remotely connect to and control mobile devices around the world in order to test mobile content."]}
{"digitalsmiths": ["Makes software in the rapidly growing niche of video search and recommendation. Its Seamless Discovery product increases the accuracy and ease with which end users find relevant, personalized entertainment across multiple channels and devices. Customers include NASCAR and Technicolor."]}
{"digitaria-interactive": []}
{"direct-agents": ["Partners with publishers and advertisers to launch and manage marketing campaigns online. The agency develops affiliate programs, social media campaigns, display ads and email marketing material for businesses of all sizes."]}
{"direct-incorporation": ["Direct Incorporation assists small businesses and entrepreneurs with their basic start-up needs."]}
{"discoverorg": ["Operates and maintains an up-to-the-minute database of contact information culled from the IT departments of corporations, educational institutions, and government organizations. The information is used as sales and marketing prospects by technology vendors."]}
{"dow-networks": ["Provides international call centers, hotels, and other businesses with VoIP networks and equipment."]}
{"drakontas": ["Drakontas provides software, technology consulting, and training programs to federal, state, and local governments, serving defense, law enforcement, criminal justice, and transportation agencies. It company specializes in the development, trial, and evaluation of communications tools, like DragonForce, its situation awareness software framework for the criminal justice community."]}
{"drupal-connect": ["Offers Drupal development, training, and staffing services to more than 100 clients across North America and Europe, including Sony Music and NYSE."]}
{"duo-consulting": ["Duo Consulting provides Web development and design services including content management, search engine optimization, and Web site usability."]}
{"dyn": ["Provides Internet infrastructure services that power domain name systems (DNS) and e-mail delivery for businesses of all sizes and for personal users. Customers include Twitter, Zappos and Netflix."]}
{"eagleview-technologies": ["The inventor of patented software that produces very detailed and accurate 3D aerial roof measurement reports for the construction and insurance markets. The reports are used to calculate solar exposure, to get exact measurements for reroofing jobs, and to make adjustments to building capacity for insurance purposes."]}
{"eclinicalworks": ["Offers comprehensive electronic health records and practice management services, allowing medical practices to improve efficiency and enhance patient care regardless of practice size, specialty, or number of locations. More than 60,000 medical providers and 370,000 medical professionals across all 50 states use its technology, including physician practices, outpatient departments of hospitals, health centers, departments of health, and convenient care clinics."]}
{"ecoast-sales-solutions": ["eCoast Sales Solution provides outsourced sales and marketing services for technology companies."]}
{"element-payment-services": ["Provides a payment processing platform to merchants and business management software providers that is easy to integrate, supports advanced technologies, and manages more than $6 billion in transaction volume annually."]}
{"emma-email-marketing": []}
{"empower-research": ["EmPower Research performs market research, media monitoring and reporting, and data extraction, analysis, mapping, and management services for retailers, telecoms, PR firms, and health care, consumer goods, and food and beverage companies."]}
{"enspire-learning": ["Enspire Learning develops e-learning courses in sales and leadership for large companies."]}
{"epocrates": ["Provides drug reference tools and other interactive services used on mobile devices by health care professionals to help them make more informed prescribing decisions, enhance patient safety, and improve practice productivity. Its user network of more than a million health care professionals includes 40% of all physicians in the U.S. Epocrates filed for an IPO in February, 2011 and raised $86.4 million before costs. This is Epocrates third IPO attempt: in 2008 it filed for a $75 million IPO, but withdrew it because of the economic downturn. Last summer Epocrates filed for another $75 million IPO."]}
{"escalate-media": ["Acquires, builds, and maintains online communities for people interested in building construction, home and garden, women's issues, and technology. Escalate Media also operates a performance-based affiliate network (Escalate Network) that brings together affiliates and online advertisers as partners."]}
{"eset": ["Develops software that detects and guards against security threats, including spyware, viruses, and spam."]}
{"etouches": ["Develops an event management software platform that allows clients such as Dell and Goodwill Industries to plan, manage, and market their entire event portfolio. Etouches serves corporations, nonprofits, associations, educational institutions, and marketing and event agencies."]}
{"evolve-ip": ["Helps businesses of all sizes save money and improve efficiency by moving their applications, infrastructure, and security services to the cloud. Evolve IP's suite of cloud services includes business applications, such as unified communications, hosted call center services, e-mail, and virtual desktop; infrastructure, such as networks, switches, and virtual servers; and security services at both the user and network level."]}
{"exacttarget": ["Provides cross-channel, interactive marketing software-as-a-service that helps organizations of all sizes to communicate with their customers through e-mail, mobile devices, social media, and the Internet."]}
{"exinda": ["Makes software that enables users to see, control, accelerate, and optimize the traffic on their wide area networks (WANs), which helps network managers maximize network resources, control operational costs, and improve user experience."]}
{"extension-engine": []}
{"facebook": ["Runs a social networking platform that connects users with friends and family, offering them tools to share and express what matters to them. Monetizes its network through targeted display advertisements and revenue share from sales of virtual goods."]}
{"fashionphile": ["Fashionphile is a family-owned company that resells second-hand handbags from Louis Vuitton, Chanel, Gucci, and other luxury designers. Founder Sarah Davis started the company as a way to pay off her law school loans."]}
{"fastspring": ["Makes software that streamlines e-commerce for merchants of downloadable and subscription-based products and services such as downloadable software, software-as-a-service, Web 2.0 services, games, and e-books. The company offers customized, hosted order pages that integrate with its clients' existing websites and design."]}
{"first-impression-interactive": ["Offers interactive marketing and generates online leads for network marketing companies, debt relief service providers, traditional and online colleges and universities, financial institutions, auto dealers, and insurers. It also provides e-mail marketing, comprehensive list management, and media buying services."]}
{"fog-creek-software": ["Develops Web-based software, mostly for use within the software industry itself, allowing teams to coordinate tasks."]}
{"folica": ["Sells hair, nail, and other beauty products and supplies online to consumers and salons, at retail and wholesale prices."]}
{"four-winds-interactive": ["Creates digital LCD, plasma, and LED display signage featuring media playback, sophisticated data integration, digital wayfinding, and interactivity. Its displays are used in numerous applications, including digital donor walls, flight arrivals and departures, interactive information kiosks, and emergency messaging."]}
{"frayman-group": ["Provides enterprise risk management software for law firms to help them automate business processes, mitigate risk, manage compliance, and improve competitiveness."]}
{"freewebs": ["Provides all the tools needed for users to create their own free custom websites within a matter of minutes."]}
{"freightcenter": []}
{"fundinguniverse": ["FundingUniverse matches qualified entrepreneurs with investors, banks, and other funding sources."]}
{"funmobility": ["Publisher of mobile phone applications ranging from wallpapers to ringtones, photosharing, and videosharing."]}
{"fusionapps": ["Develops mobile apps and provides user experience and managed infrastructure services."]}
{"fuzz-productions": ["Implements digital strategies, designs mobile apps, and makes websites more user-friendly and interactive for clients such as the Hollywood Reporter and Ford Models."]}
{"gemvara": ["An online retailer of fine jewelry that offers 1,500 original designs that can be customized using 26 gemstones and eight precious metal options."]}
{"geneca": ["Designs customized software for data analysis, customer relationship management, and automated business processes."]}
{"geomagic": ["Geomagic is a software company that designs 3D modeling and inspection software to aid in data imaging and transport."]}
{"glispa": ["Advises clients on media planning and buying strategies. Glispa, which refers to a goddess of healing in Navajo mythology, also does mobile, affiliate, and search marketing for its clients."]}
{"glowtouch-technologies": ["Offers tech support and back office services for Web hosting companies and custom application development for health care and tech product companies."]}
{"godaddy": []}
{"gogo": ["Delivers branded in-flight Internet connectivity that allows air passengers to get online on more than 1,500 commercial and 5,000 private business aircraft. In 2006, the FCC awarded Gogo its exclusive air-to-ground (ATG) 3Mhz broadband frequency license, which allowed it to build an uninterrupted network across the continental U.S."]}
{"govdelivery": ["GovDelivery offers hosted email and digital subscription management services for federal, state, and local government agencies and transportation authorities in the U.S. and some government clients in the U.K. The company's blog reachthepublic.com offers irreverent, humorous advice about government communications, including the use of social media."]}
{"granicus": ["Granicus offers webcasting services that enable its clients - schools, colleges, public access channels, and city and state governments - to deliver public meetings, service announcements, educational content, and video training through the Internet, live or on-demand."]}
{"greenleaf-book-group": ["Produces, markets, and distributes self-published books in many genres. It also distributes select titles from small and independent publishers to major trade outlets, libraries, and airport retailers."]}
{"grosolar": ["groSolar delivers and installs solar power systems for residential and commercial customers."]}
{"headsets-com": []}
{"health-dialog": ["Provides health-care management and analytical services for large employers, provider groups, and government programs."]}
{"healthfusion": ["Internet-based company providing medical-claims processing services."]}
{"hostgator": ["HostGator provides shared Web hosting, dedicated services, and reseller hosting to webmasters, small businesses, and hobbyists that have content to share nationwide."]}
{"hosting-com": []}
{"house-party": ["Organizes \"house parties\"events hosted by \"brand advocates\" selected from its community of social influencers to spread authentic brand recommendations to millions. Over the course of each eight to 12-week campaign, the hosts engage with one another and drive social media activity by creating and sharing user-generated content. Campaigns include Ladies' Night In\" parties for the Meryl Streep movie Hope Springs and kids' \"Read and Build\" parties for Lego products."]}
{"hydramedia": ["Matches advertisers like Kraft with a network of affiliated website publishers including MySpace."]}
{"icims": ["Sells Web-based business software primarily used by corporate HR departments for help with recruitment and hiring."]}
{"icontact": ["iContact?s e-mail marketing software enables nonprofits, associations, and businesses like AT&T, International Paper, and Viacom to easily create, send, and track e-mail newsletters, RSS feeds, surveys, and autoresponders. The company has more than 60,000 customers throughout the world."]}
{"icrossing": ["iCrossing assists large companies such as Toyota, Epson, and Coca-Cola with digital advertising and search engine marketing. The company has 12 offices across the U.S. and Europe. The Wall Street Journal recently ranked iCrossing as one of the Top 50 Venture-Backed Companies."]}
{"idata": ["Provides technology consulting and software services company to colleges, universities, and research institutions. Offerings include programming and analysis and institutional research services"]}
{"ideeli": ["A members-only retail site offering a curated selection of apparel, accessories, shoes, and home and travel items. Each sale starts at noon EST and lasts 40 hours. The shopping site has more than 4 million members."]}
{"ifbyphone": ["Develops a voice-based marketing automation platform that helps businesses manage, measure, and automate their online and off-line lead activities. More than 3,200 companies from a variety of industries use Ifbyphone to enhance lead capture, lead response, lead scoring, lead nurturing, and analytics for sales processes that include voice communications."]}
{"ignite-social-media": ["Focuses solely on social medi marketing. The agency's four core tenetsstrategy development, campaign execution, community management and reportingguide its team of more than 70 employees in addressing the major disciplines: engagement, tech, creative and SEO. Its clientele includes Microsoft Windows and The Body Shop."]}
{"igodigital": ["Makes software that helps businesses personalize their customer interactions online. Its product recommendation service personalizes a customer's shopping experience through websites, e-mails, mobile devices, call centers, and stores. It serves retailers, manufacturers, and content providers of all sizes."]}
{"impinj": ["Provides radio frequency identification (RFID) microchips, readers, and related products designed to allow businesses and organizations to do things like scan and track inventory.  Impinj filed for an IPO in April 2011."]}
{"improving-enterprises": ["Develops software and offers advanced technology training, certified consulting, networked recruiting, applied training, and rural sourcing, through which it recruits local college students in remote areas for application development."]}
{"incentive-logic": ["Incentive Logic operates Web-based points programs and direct incentives to motivate clients' employees and customers."]}
{"indisoft": ["Develops software for the default management industry that offers complete transparency to all participants in the process. Its flagship RxOffice platform allows stakeholders to identify delays and gives all parties access to information. RxOffice Legal offers case, document, and workflow management, and MortgageRx provides servicers a consistent and compliant way to control key processes while managing multiple auditing requests and adhering to best practices."]}
{"infusionsoft": ["Develops all-in-one sales and marketing software used by small businesses to convert more leads, increase sales, and save time."]}
{"inlet-technologies": ["Inlet Technology provides a suite of video encoding software designed to output content that scales seamlessly from mobile to web to high-definition, ideal for a wide variety of digital media applications such as broadcasting live events over the Internet, building a video-on-demand library, or creating Blu-ray discs. Inlet helps companies both large and small optimize video production workflow and increase throughput."]}
{"intela": ["Offers services in online lead generation and e-mail marketing. It has reached 30 million households and delivers more than 50,000 leads daily."]}
{"intergi": []}
{"intergi-entertainment": ["Helps gaming websites monetize their content with advertising from major brands. Its customers include Ubisoft and Activision/Blizzard. It recently launched Playwire.com, and owns and operates GameZone.com."]}
{"intronis": ["Offers Internet-based backup and disaster recovery services for the IT industry."]}
{"invitation-consultants": ["Invitation Consultants sells personalized invitations, announcements, stationery, holiday cards, gifts, and party favors."]}
{"ionic-media": ["Ionic Media creates advertising and branding campaigns. Clients have included Disney, Marriott and Verizon Wireless."]}
{"ipexpert": ["IPexpert provides training in Cisco technology through audio and video learning tools, workbooks, online hardware access, and instructor-led online training courses."]}
{"ipnetzone-communications": ["Provides international data, Internet, multiprotocol label switching (MPLS), and managed network and monitoring services for enterprise and carrier clients."]}
{"jobapp-network": ["Provides an automated phone- and Web-based hiring management system for companies with large, decentralized workforces. JobApp sources, screens, and scores applicants, streamlining hiring and reducing turnover. The service features for applicant tracking, behavioral assessments, background checks, credit checks, tax form compliance, and training."]}
{"keylimetie": ["A website and mobile design and development and digital strategy agency that helps clients communicate more effectively and closely with their customers through interactive marketing channels. It provides content management, e-commerce, and custom application services and assists customers with social media campaigns and online reputation management."]}
{"lai-international": ["Sells precision components and subassemblies to equipment manufacturers in the aerospace, power generation, and defense industries. The company has developed advanced technologies using laser, waterjet, EDM, CNC machining and other processes to provide unique manufacturing solutions to customers."]}
{"latisys": ["Provides IT managed services, data center colocation, managed hosting and virtualization, and enterprise cloud services."]}
{"lattice-engines": ["Lattice Engines helps customers maximize their return on sales and marketing investments. Its software combines advanced optimization techniques and predictive analytics built on a flexible data integration platform."]}
{"lawcrossing": ["Manages an online job board for the legal industry."]}
{"layered-technologies": ["A global IT company, Layered Technologies specializes in managed dedicated hosting, on-demand grid/virtualization computing, and Web services."]}
{"leadnomics": ["Generates millions of new leads every year for financial institutions and insurance companies across the U.S. and the U.K. It specializes in finding the right customers for its clients by running highly targeted campaigns across a variety of online channels."]}
{"leapfrog-interactive": ["Provides Internet marketing services specializes in helping its clients build engaging, online brand interaction with consumers."]}
{"lendio": ["Matches small business owners with the banks, lenders, and other funding sources most likely to underwrite their small business loans. If a company is not ready for a loan, Lendio offers services to prepare it for one, such as business plan analysis, financial statement analysis, and incorporation services."]}
{"levelwing": ["Mines and analyzes data to help businesses market and operate with greater clarity and profitability. Levelwing customizes its digital marketing services to grow and improve its clients' business through strategy development, creative, integrated marketing, technology, and business intelligence."]}
{"liazon": ["Operates an online benefits exchange for small and midsize businesses. Its flagship product, the Bright Choices Exchange, is an online benefits store that helps employers save on average 10 percent to 30 percent annually on their health care costs by setting predictable budgets while guiding employees to purchase better coverage of health, dental, vision, life, and disability benefits."]}
{"linkedin": ["Provides a professional social media network for more than 100 million members. The company went public in May 2011."]}
{"linode": ["Provides highly customizable, Linux-based virtual servers to companies of all sizes."]}
{"liquidspoke": ["LiquidSpoke specializes in integrated systems and infrastructure management. LiquidSpoke's \"global delivery approach\" relies on outsourcing to minimize risk and maximize flexibility."]}
{"livestream": ["Enables live, streaming event coverage, allowing anyone to broadcast live to the Web. Its clients include Facebook, the New York Times, and TV networks."]}
{"local-splash": ["Helps clients get high rankings on local search sites like Google, Yahoo!, Merchant Circle, Yelp, and many others. Its proprietary search engine marketing technology especially benefits businesses that target customers by geographic area. Clients range from local businesses to large national chains such as Extra Space Storage."]}
{"location-labs": ["Provides advanced location-based software that allow third-party developers to build applications that enables users to share their mobile phones' location."]}
{"location3-media": ["Specializes in directing Internet traffic to clients' websites."]}
{"logica": ["Audits shipping invoices to get refunds on overcharges for its clients, mid-market and high volume shippers. It also provides Web analytics on shipping data and negotiates better rates with carriers on behalf of its clients."]}
{"logixml": ["Manufactures business intelligence software that helps clients turn data into business critical information."]}
{"luggage-forward": ["Takes luggage to an individual's destination ahead of arrival, in locations throughout the world. Luggage Forward eliminates waiting in airport baggage lines, coming and going."]}
{"lumension": ["Lumension sells data protection software for corporate, government, and international clients, including NASA, Virgin Atlantic, and Google."]}
{"m5-networks-3": []}
{"magic-logix": ["Magic Logix is a website design and digital marketing company that focuses on business growth through technology. It offers search engine optimization, social networking development tools, e-commerce services, open source Web development, blog integration and customization, and Internet marketing."]}
{"majestic-research": ["Majestic Research assists institutional investors with equity research."]}
{"mapmyfitness": ["Operates a suite of social wellness-oriented websites and associated mobile and tablet applications including MapMyRUN.com and MapMyHIKE.com. MapMyFITNESS provides more than nine million runners, cyclists, walkers, and other fitness enthusiasts access to a geo-mapping application that permits them to track and store their daily running, cycling, walking, or hiking routes, a searchable database of routes across the globe, community-based fitness content, online training tools and fitness calculators, comprehensive global event listings, and a dynamic social network of healthy and active individuals."]}
{"marketo": ["Develops marketing automation and sales effectiveness software that increases revenue performance."]}
{"marlabs-inc": []}
{"mavenir-systems": ["Offers mobile infrastructure services to operators that provide LTE and mobile cloud services. Its IP-based core network services migrate voice and messaging to LTE."]}
{"max-borges-agency": ["A PR firm for the tech sector that focuses exclusively on consumer electronics and enterprise technology. Clients include 4moms and Ballistic."]}
{"mediamath": ["Operates the TerminalOne platform, which allows agencies and advertisers to plan, execute, optimize, and analyze marketing programs across the digital landscape."]}
{"mediatrust": ["MediaTrust offers a diverse set of digital marketing services for advertisers using affiliate Web page publishers. The company's proprietary cost-per-action platform supports campaigns using display advertising, paid search, social media, and e-mail."]}
{"mediawhiz": ["Combines expertise in all forms of online marketing (display, search, social, email, affiliate, mobile, etc.), focusing on media ROI for a broad range of leading advertisers."]}
{"medseek": ["Provides software to help health care organizations attract potential patients, engage patients and their families, coordinate care, and improve operational efficiency."]}
{"medsynergies": ["Partners with health care organizations and physicians to align their operations by providing revenue cycle management, practice management, consulting services, business process analysis and software integration services."]}
{"megameeting-com": []}
{"metova": ["Develops smartphone applications for customers such as Barnes & Noble and eHarmony."]}
{"millennial-media": ["Specializes in mobile advertising, helping publishers and developers to maximize ad revenue, mobile operators to further monetize their networks, and advertisers to reach mobile consumers."]}
{"mindbody": ["Delivers innovative business management software to nearly 18,000 subscribers in the health/wellness industry worldwide. The company's web-based software helps businesses increase annual sales by an average of 14% with features like online scheduling, staff and client management, integrated marketing tools and e-commerce solutions."]}
{"mocospace": ["Offers mobile Internet entertainment applications to more than 25 million registered users."]}
{"modcloth": ["Founded by husband and wife team Eric Koger and Susan Gregg Koger, ModCloth is an online retailer that sells affordable women's fashions from independent designers. Its unique selection of indie clothing and engaging promotions on the ModLife blog and social networks have attracted a devoted following. ModCloth has almost 13,000 followers on Twitter and more than 30,000 fans on Facebook. More than 150,000 Web pages on the Internet link to ModCloth.com, and the company is the top result in Google searches for indie clothing, retro clothing, and vintage outfits."]}
{"modea": ["Digital ad agency that offers strategic, marketing, creative, and technology services to consumer brands such as Hasbro and T-Mobile."]}
{"model-metrics": ["Model Metrics specializes in cloud computing services and is a Salesforce.com partner, Amazon Web Services charter partner, and a Google Enterprise Reseller. Its customer base spans all industries and includes enterprises such as Cars.com, Honeywell, MasterCard, and Orbitz."]}
{"modern-survey": ["Modern Survey offers business intelligence consulting with a focus on human capital management."]}
{"monavie": ["MonaVie develops and markets beverages and nutritional supplements based on the health benefits of the Brazilian a\u00e7ai berry. Its products and marketing strategy are designed exclusively for person-to-person distribution."]}
{"motivequest": ["A consumer research and consulting company. It consults with clients regarding emerging consumer trends online and with major brand leaders in the national corporate marketplace."]}
{"mozes": ["A mobile engagement company focused on connecting companies to their audiences using the mobile phone, particularly at live events. Using Mozes Connect, marketers can create, manage, promote, and analyze mobile marketing campaigns that not only make events more fun, but also enable them to continue the consumer relationship after the event ends. Customers include Rock the Vote and the Country Music Association."]}
{"mr-youth": ["Mr. Youth provides non-traditional marketing services to corporate advertisers hoping to reach the 14- to 24-year-old market."]}
{"mspot": ["mSpot operates a service, provided through 10 wireless carriers, that allows consumers to access music, custom ringtones, live radio, and videos from major music labels, movie studios, and top brands on their mobile phones."]}
{"mtbc": ["Offers a suite of fully-integrated, end-to-end services which help physicians and practices simplify every step of the practice management process, from the initial scheduling of an appointment to the billing and remittance tasks."]}
{"my-computer-works": ["Provides help desk and personal computer support services for thousands of small businesses and consumers nationwide. Most of its assistance is provided remotely by technicians via the Internet, although it also makes on-site visits when necessary. It has technicians located in all 50 states."]}
{"mybuys": ["Helps retailers increase the effectiveness of their marketing strategy by learning individual consumers tendencies and interests, then using this intelligence to present these shoppers with optimized recommendations and offers."]}
{"mywedding": []}
{"myyearbook": ["A social network for meeting new people, dating, games, virtual goods, and social applications. myYearbook started in a single high school in 2005 and has grown to more than 25 million members worldwide."]}
{"nasty-gal": ["Sells new and vintage clothing, accessories, and shoes online. Founder Sophia Amoruso started the company on eBay, selling one-of-a-kind vintage pieces that she sourced, styled, photographed, and shipped herself."]}
{"netcordia": ["Netcordia sells network automation software used by the health care and financial services industries, as well as academia and government organizations. Its flagship product NetMRI continuously audits multi-vendor infrastructures, identifies anomalies, and speeds resolution."]}
{"netsuite": ["NetSuite offers an online software subscription service that helps small and midsize retailers manage various aspects of their business."]}
{"netwrix": ["Makes specialty software for IT infrastructure change auditing, which allows detailed tracking of who made what changes in the system. The software helps to control unauthorized changes, prevent costly security breaches, and sustain compliance."]}
{"new-media-strategies": ["Analyzes consumers' opinions of brands and products as expressed in chat rooms, blogs, and other online venues. New Media then helps customers--large marketers like McDonald's, Disney, and Reebok--spread the good word and defend against the bad."]}
{"nimsoft": ["Nimsoft monitors IT-based business applications and services for more than 780 customers in 36 countries."]}
{"obtiva": ["Provides agile software development services for organizations that need to create custom web and mobile applications specializing in Ruby on Rails. Delivers cutting-edge training,led by some of the technology community's top consultants."]}
{"odesk": ["Specializes in recruitment and job placement services for Web developers, software programmers, graphic designers, writers, and customer service representatives. More than 2.8 million hours were worked on oDesk's platform in March 2012 alone, for which oDesk receives a 10% commission on payments."]}
{"one-source-networks": ["Provides managed voice and data services, delivering ubiquitous access to cloud-based voice, security, and computing applications that power a mobile, global workforce. One Source Networks delivers all of its voice and data services to its clients under one contract, with one account and service team, on one invoice."]}
{"one-source-talent": ["Assists models, actors and other specially talented individuals in entering the entertainment industry while providing a medium for casting directors, clients and agencies to locate talent"]}
{"onescreen": ["A digital video solutions partner with a full-service platform that includes content management, rights management, and syndication for producers, cross-platform video players, applications, and monetization for publishers, and advertising serving, targeting, and analytics for advertisers."]}
{"opensky": ["An IT consultancy focused on helping organizations reduce costs, protect information assets, and accelerate the adoption of technologies that will make their business grow and improve. Its four practice areas are core infrastructure; technical business consulting; IT risk management and security; and governance, risk, and compliance."]}
{"operative": ["Develops Software-as-a-Service-based platform and technology-enabled services and software designed to assist digital media companies in streamlining ad operation efforts. Companies can use its services and software to package, sell, traffic, manage, optimize and collect revenue on multiple advertising products."]}
{"opticsplanet": ["Sells a wide selection of optical products such as microscopes, radar guns, binoculars, and GPS equipment, for the educational, scientific, outdoor, military and consumer markets."]}
{"orange-legal-technologies": ["Performs electronic discovery, litigation support, business audits and internal investigation services for law firms and corporations."]}
{"orangesoda": ["Uses a combination of search technology and industry and consumer behavior expertise to offer online marketing services to local businesses."]}
{"oversee": []}
{"paisley": ["Designs and sells software for managing corporate governance, regulatory compliance, and risk."]}
{"palo-alto-networks": ["Develops a software platform that allows enterprises, service providers, and government entities to secure their networks and safely enable the large number of complex applications running on them."]}
{"pandora": ["An Internet radio company that creates personalized radio stations for more than 50 million listeners in the U.S. By entering favorite artists or songs, listeners can build up to 100 unique, personalized stations. Since 2000, the company's music analysts have been listening to music, one song at a time, studying and collecting details about melody, harmony, instrumentation, rhythm, vocals, and lyrics for every trackwhat it calls the Music Genome Project. Listeners can access their stations via computers, smart phones, TVs, and more than 100 other connected consumer electronic devices. Pandora filed for an IPO in February 2011."]}
{"pardot": ["Makes marketing automation software that gives its clients detailed analytics on their Web visitors and prospects and helps them increase their ROI."]}
{"paylease": ["Facilitates electronic payments for the property management industry, specifically for multifamily, single family, homeowners association, and commercial markets."]}
{"payscale": ["Creator of a database of job compensation profiles that provides a snapshot of current market salaries to employees and employers through online tools and software. Its 2,200 corporate customers include Zappos and Manpower."]}
{"pcg-digital-marketing": ["A full-service agency that specializes in helping businesses with their online presence to increase traffic, relevancy, and profits."]}
{"peoplenet": ["Provides mobile communications and onboard computing services for transport fleets."]}
{"pepperjam": ["Internet marketing agency that provides search-engine marketing and online-media-buying services."]}
{"plastyc": ["Provides FDIC-insured bank accounts that consumers can access 24 hours a day through any Internet-connected device. Its services include prepaid credit cards, person-to-person transfers, direct deposit of paychecks, and discount prescription drug cards."]}
{"playnetwork": ["PlayNetwork provides branded in-store music, digital signage, promotion, and other media solutions for music brands sold in retail and department stores."]}
{"praxis": ["Designs, manufactures, and distributes clamshell, blister, and stretch-card packaging."]}
{"prenova": ["Assists companies with control energy-related spend by reducing utility costs and improving energy efficiency. The company partners with clients to develop an energy strategy that fits their unique business needs."]}
{"prime-insurance-agency-2": []}
{"printglobe": ["Sells customized promotional products online, including keychains, drinkware, apparel, bags and totes, and school supplies. It also provides custom and business printing of brochures, labels, business cards, and presentation folders."]}
{"procpr": ["ProCPR provides Web-based training services in CPR, first aid, and other Occupational Safety and Health Administration (OSHA)-mandated areas."]}
{"prodege": ["Operates Swagbucks.com, which rewards consumers for their online activities with virtual currency that they can redeem for real life rewards, goods, and services."]}
{"qliktech": ["QlikTech's business intelligence software, QlikView, allows users to intuitively analyze data to make important business decisions fast. The company went public in July."]}
{"quality-logo-products": ["Supplies a full range of imprinted promotional products. Quality Logo Products offers thousands of items, stock and custom."]}
{"qualitysmith-2": []}
{"quantum-retail": ["Quantum Retail sells software to assist large retailers with inventory planning, allocation, and replenishment."]}
{"quickoffice": ["Develops software that allows users to view, edit, and create Microsoft Word, Excel, and PowerPoint documents on their mobile devices, whether their documents are stored on another device or on the cloud."]}
{"rally-software": ["Develops application lifecycle management software that helps software development teams collaborate and manage their projects."]}
{"rapid7": ["A security IT company that provides vulnerability management, compliance, and penetration testing services."]}
{"reachlocal": ["ReachLocal helps small and midsize businesses acquire and retain customers online. It offers comprehensive online marketing and reporting services, including search engine marketing, display advertising, remarketing, and online marketing analytics."]}
{"readytalk": ["Provides user-friendly audio and Web conferencing services. It offers a variety of audio conferencing options, Web conferencing tools, and sophisticated recording and archiving services."]}
{"realself": ["A site that contains information for consumers about elective cosmetic medical procedures, including cosmetic dermatology, plastic surgery, cosmetic dentistry, massive weight loss, hair replacement, and vision correction. The site features reviews and ratings of doctors as well as firsthand accounts and opinions of various procedures."]}
{"red-bricks-media": ["Red Bricks Media is a global, full-service advertising agency offering search engine marketing, interactive media planning, e-mail campaign management, creative services, and emerging strategies such as mobile and viral marketing."]}
{"red-clay-interactive": ["Red Clay Interactive provides internet marketing, as well as web design and application development."]}
{"reddwerks": ["Develops warehouse performance management software that manages labor, equipment, and material flow and automates order processing in large-scale distribution facilities. Customers include A Pea in the Pod and Williams-Sonoma."]}
{"refinery29": ["A website that is updated daily with news, trends, and shopping deals in fashion, beauty, and entertainment. The site attracts 5 million visitors, and has editions for seven metropolitan areas in the U.S."]}
{"reflexis-systems": ["Reflexis Systems provides retailers with software designed to coordinate manager workloads, communication and inventory information, and encourage in-store compliance with corporate marketing strategies."]}
{"remitdata": ["Sells Web-based services to assist outpatient health care providers with reimbursement, utilization, and productivity."]}
{"rfid-global-solution": ["Develops and distributes real-time asset management tools for the data center and enterprise asset tracking markets. Its software platform is designed to improve operations and logistics, and includes IT asset tracking, inventory management and work-in-process applications. Its clients are found in the aerospace, communications, financial, and healthcare industries."]}
{"rise-interactive": ["Internet marketing company that serves companies of all sizes, from startups to major corporations all over the world. Its specialized services include search engine optimization (SEO), paid search, affiliate marketing, display advertising, e-mail marketing, social media, reputation management, and web analytics consulting."]}
{"rivet-software": ["Develops the Crossfire platform, which enables integrated financial reporting analytics with XBRL (extensible business reporting language, a way of tagging financial documents with machine-readable code for transmission over the Internet). The software saves businesses time, ensures accuracy, and minimizes risk."]}
{"rockfish-interactive": ["Offers a host of digital-focused services, from marketing research and strategy and search engine optimization to brand identity and social media campaigns. One of its major projects is Pocket Grin, an iPhone gaming app for Listerine."]}
{"room-214": ["Provides social media and digital marketing for new and established brands. Its digital marketing campaigns include custom research, strategy, and execution. It offers online client engagement tools, advertising, video production, creative design, blog, Facebook, social media platform and mobile site development, as well as dashboards for marketing."]}
{"savo": ["Makes sales enablement software that opens up lines of communication for sales teams, connecting them with sales materials, tools, insights, and expertise to help them work more efficiently."]}
{"sciencelogic": ["ScienceLogic manages integrated systems, networks, and business-critical applications for midsize companies."]}
{"sciquest": ["SciQuest sells Web-based software to assist education, government, health care, and life sciences organizations with strategic procurement and supplier management."]}
{"seamlessweb": ["Helps corporations feed their people. Using SeamlessWeb's online service, companies can have meals delivered to workers at their desks, arrange to have an event catered, order a birthday cake or gift basket, and replenish office pantry items like coffee. In return, SeamlessWeb ensures delivery and collects a transaction fee."]}
{"search-mojo": ["Specializes in search engine optimization (SEO), pay-per-click (PPC) advertising management, and post-click marketing to drive B2B lead generation. It now also offers online reputation management and social media monitoring, and has helped nonprofits get the Google Grant, the program for free AdWords advertising for charitable organizations."]}
{"secondmarket": ["SecondMarket is the largest centralized marketplace and auction platform for illiquid assets, such as asset-backed securities, auction-rate securities, bankruptcy claims, collateralized debt obligations, limited partnership interests, private company stock, residential and commercial mortgage-backed securities, restricted securities and block trades in public companies, and whole loans. SecondMarket's online auction platform has more than 10,000 participants, including global financial institutions, hedge funds, private equity firms, mutual funds, corporations, and other institutional and accredited investors that collectively manage more than $1 trillion in assets available for investment."]}
{"secureworks": ["Fffers a wide range of IT-based security services to more than 2,800 organizations."]}
{"seomoz": ["Develops search engine and social optimization software with tools and tutorials that enable businesses of all sizes to increase traffic to their sites."]}
{"sesame-communications": ["Collaborates with clients in the dental industry on their web design, online marketing, site optimization as well as managing social media accounts and overall Web presence."]}
{"sevone": ["Provides application-aware, network performance management software that enables enterprises, cloud and service providers, and government organizations to keep increasingly complex networks, servers, and applications functioning at peak performance levels."]}
{"sharefile": ["Its software allows companies to create a custom-branded, password-protected area where they can exchange business files with clients easily, securely, and professionally. Lawyers, film producers, photographers, graphic designers, engineers, and health care professionals use ShareFile when they have files too large to e-mail or need a collaboration space where project-related files can be posted."]}
{"shutterfly": ["Makes it possible for members to print, enhance, share, and store digital photos online."]}
{"siteworx": ["Siteworx provides Web and mobile interactive design and technology to clients in the government, commercial, and nonprofit sectors."]}
{"sittercity": ["Sittercity is an online resource for any kind of care providers, including babysitters, nannies, pet sitters, senior companions, housesitters, housekeepers, and tutors. The company currently serves more than 33 cities across the nation and has expanded its services to include corporate child care programs and a referral program."]}
{"skiphop-com": []}
{"smile-reminder": ["Provides a contact management software system that enables client health care organizations to easily send text or e-mail appointment reminders, birthday greetings, and e-newsletters, and to operate patient portals and testimonial sites."]}
{"softvu": ["Develops software to help companies create, manage, distribute and track online content and communications."]}
{"softweb-solutions": ["Specializes in software development and consulting services for mobile and web applications. Softweb develops and tests software for clients in healthcare, entertainment, IT and finance."]}
{"solutionset": ["Creates business, marketing, and technology services to assist clients in building brands. The company specializes in relationship marketing, digital services, data management and local marketing in order to offer clients a complete, customized service for various marketing needs."]}
{"sonicbids": ["Gives more than 100,000 musicians from 100 countries the tools to create electronic press kits. These packages, which include MP3s, text, pictures, and video, can be e-mailed to event promoters. The musicians pay Sonicbids an annual membership fee of $50 to $100."]}
{"sonoma-partners": ["Provides technology and business process consulting services to enterprise and mid-sized companies throughout the United States and Canada, with a focus on the Microsoft Dynamics CRM product."]}
{"southwest-windpower": ["Designs and distributes small wind turbines."]}
{"spadac": ["SPADAC provides decision support and data analysis through technology and services focusing on geospatial intelligence and predictive analytics, for clients in the defense and intelligence, homeland security, oil and gas, transportation and logistics, federal civilian, and insurance markets."]}
{"sparkfun-electronics": ["Enables individual customers to create their own embedded electronics projects through supplying small consumer electronic parts and tools. Manufactures, tests, packages, and distributes its own open source hardware products."]}
{"sparta-systems": ["Provides quality and compliance process management software, mostly for the life sciences industry."]}
{"speck-products": ["Designs and manufactures cases for iPods, cell phones, satellite radios, and Apple laptops."]}
{"spring-creek-group": ["Offers social media brand analytics, strategy, and marketing services for companies like CH2M Hill and LiveNation.com."]}
{"spring-wireless": ["Processes transactions for enterprises worldwide, including leading companies like Coca-Cola, Kellogg\u2019s, L\u2019Or\u00e9al, P&G, PepsiCo, Unilever, and Citibank. Its mSeries platform enables business to improve mobile workforce effectiveness, exchange real-time data and insights across field processes, and build mobile channels and relationships with consumers."]}
{"springahead": ["Develops a platform for time and expense tracking that integrates with numerous types of accounting software and is used by staffing agencies, professional services businesses, accountants, and organizations that need to comply with government regulations."]}
{"springboard": ["Places radiation/oncology and radiology professionals on a contract and permanent basis at hospitals and cancer centers nationwide."]}
{"squarespace": ["Its software powers websites for businesses, bloggers, and professionals worldwide."]}
{"standing-dog": ["Provides Internet marketing services and develops websites primarily for hotels and resorts. Major clients include Marriott, Event Cinemas, Omni Hotels, Miraval Resort."]}
{"starcite": ["StarCite provides web-based software to help buyers and suppliers manage very large corporate meetings and events, with a focus on cost savings and increased productivity."]}
{"stella-dot": ["Sells jewelry through its network of commission-earning stylists, individuals who sign up with the company to host trunk sales of the merchandise in their local communities. Stylists can earn additional income by becoming coaches who lead and teach groups of newer stylists."]}
{"stride": ["Manufactures and sells writing instruments and other office products. The company has a mission of employing people with developmental disabilities."]}
{"strikeiron": ["Provides data and communication via its cloud platform for a variety of applications. It supplies bulk text messaging marketing from business to customer. It has an application for real-time sales tax calculations for online shopping carts. Products are delivered through online services that integrate into a variety of platforms."]}
{"studypoint": ["Provides one-to-one in-home private test prep and tutoring for students in grades K-12. Its nationwide offices have assisted over 15,000 students since its inception."]}
{"stumbleupon": ["StumbleUpon is an online content discovery engine that brings users to pages matched to their personal preferences. Users are presented only with those websites suggested by their friends or other 'stumblers' with similar interests. The New York Times likened the experience to \"channel surfing the Internet, or rather, a corner of the Internet that is most relevant to you.\"  After a brief period of ownership by eBay, StumbleUpon was bought back to its original start-up status by its founders, backed by Silicon Valley investors, including Ram Shriram (of Sherpalo Ventures), Accel Partners, and August Capital."]}
{"substantial": ["Builds Web, mobile, and embedded applications for clients that include Kanye West and Citibank."]}
{"successfactors": ["Provides performance management software solutions."]}
{"sugarsync": ["Provides mobile cloud services that enable users to access, backup, sync, and share all of their data anytime, instantly and securely, from any Mac, PC, or mobile device. SugarSync offers the first five gigabytes of online storage for free, then the option to upgrade to one of five paid plans."]}
{"surepayroll": [" Payroll outsourcing, tax filing and payment services."]}
{"surveygizmo": ["Makes software that market research firms and companies of all sizes use to create online surveys, questionnaires and forms, allowing capture and analysis of essential business data."]}
{"sweet-spot-marketing": ["Conducts paid search and search engine optimization for small and midsize advertising agencies and Web development companies."]}
{"tangoe": ["Provides software and technology-enabled services to help global organizations manage, understand, and control their fixed and mobile communications assets and costs."]}
{"techcfo": ["Provides executive level strategy and business planning, financial operations, governance and investor relations, capital raising, transaction support and specialty services."]}
{"teknicks": ["Creates and manages Internet marketing strategies for well-known brands such as MTV and Reader's Digest, with a focus on search engine marketing."]}
{"telenav": ["TeleNav develops location-based applications for use on mobile devices, such as voice and onscreen GPS driving directions on cells and smartphones. It offers products in 29 countries with 15 carriers on more than 500 devices. TeleNav went public in May 2010."]}
{"telesphere": ["Provides a cloud-based communications system that allows businesses all the VoIP and unified communications services once reserved only for the largest companies, at low cost."]}
{"telovations": ["Designs, builds, and manages advanced communications networks for businesses."]}
{"the-jar-group": ["Assists companies with understanding online behavior to increase traffic, sales, and revenue via a suite of online marketing services including search engine optimization, paid search, digital advertising, market research, affiliate program management, CRM, analytics reporting, media buying, and social media marketing."]}
{"the1stmovement": ["Digital agency that architects, designs and builds technology solutions for leading global brands in the healthcare, technology, travel and tourism and consumer good verticals. Clients include brands like Cisco, AT&T, Reebok, USOC, Adobe, PENTAX, DaVita, HKTDC and others."]}
{"theplatform": ["Makes software that allows the owners of digital media content to distribute it in popular formats such as Windows Media, Flash, and MPEG-4 via wireless or broadband networks, to all sorts of devices, from PCs and TVs to cell phones."]}
{"three-pillar-global": ["Builds software products for businesses.  We do this through our disciplined approach to innovation and our expertise in disruptive technologies such as mobile and big data."]}
{"ticketleap": ["Provides an online exchange, integrated with social media, where tickets to concerts, theatre, and sporting events are bought and sold."]}
{"tiempo-development": ["Specializes in software development and testing from its near-shore centers in Mexico."]}
{"tigerspike": ["Designs and develops personal media campaigns for publishing groups, telecommunications brands, retail outlets, government agencies and the fast-moving consumer goods sector. Focuses on reaching consumers and assisting enterprise staff members by creating apps, content for mobile sites and messages for all types of personal and portable devices."]}
{"tm-one": []}
{"touchstorm": ["Produces and distributes video advertising online for clients such as Autodesk and Travelocity. It specializes in making HD-quality, journalistic videos that have an editorial tone and appear in the center of the page rather than at the margins."]}
{"tradeking": ["TradeKing is a nationally licensed online stock and options brokerage firm offering simple, low trading fees ($4.95 per trade plus $.65 per option contract) with no hidden costs or account minimums. A pioneer in integrating new financial social media as part of its innovative online equities, options trading, and fixed-income trading platform, TradeKing earned five stars in customer service in the June 2009 SmartMoney Broker Survey."]}
{"traffiq": ["Facilitates the buying and selling of display media, yielding maximum return on investment for advertisers, ad agencies, and publishers using it's web-based platform."]}
{"triangle-direct-media": ["Specializes in New Media Marketing Services and SEO Technology including SEO and Social Media Marketing.  SEOTool.com is a SAAS model that helps website owners uncover and fix hard to find problematic issues that are preventing them from ranking better on search engines. It has over 300 National Clients in the B2C and B2B space."]}
{"triple-creek": ["Develops enterprise mentoring systems software used by large corporations to enable knowledge sharing that transcends location, vocation, and generation. Clients include McDonald's, the U.S. Border Patrol, Monsanto and Credit Suisse (USA)."]}
{"trumpia": ["Makes an all-in-one multichannel marketing software that enables campaigns on mobile, e-mail, voice, IM, and social media platforms. Customers include Jiffy Lube and Columbia University."]}
{"tubemogul": ["Simplifies the delivery of video ads and maximizes the impact of advertising dollars spent by brand marketers by integrating real-time media buying, ad serving, targeting, optimization, and brand measurement into its PlayTime platform."]}
{"unitedlex": ["Provides litigation services, including e-discovery and document review, contract review and management, intellectual property, legal research, and immigration and law firm support. With more than 750 professionals in nine global offices and two data centers, UnitedLex reduces costs and solves complex legal and business challenges for global corporations and law firms."]}
{"usablenet": ["Translates its clients' existing website content and functionality to mobile Web and application interfaces. Major clients include ShopNBC, Amtrak, Delta, Expedia, FedEx, and Marks & Spencer."]}
{"uship": ["uShip facilitates the moving of hard-to-ship items, such as cars, furniture, pianos, boats, freight, and heavy equipment, connecting people and businesses with feedback-rated transporters. Carriers place competitive bids to win business, often filling extra space in their trucks and saving customers an average of 50% of costs. uShip has attracted $150 million in business transactions, one million listings, and 170,000 service providers for moves in the U.S., Canada, U.K., EU, and Australia."]}
{"utest": ["Utilizes a roster of more than 60,000 professional testers from 190 countries to provide real-world testing of Web, desktop, and mobile applications in development. uTest's services ensure that the applications function as intended, are free of security vulnerabilities, perform in peak traffic conditions, are intuitively easy to use, and translate well to different regions of the world. Clients include Netflix and Random House."]}
{"vendormate": ["The company's software-based products enable its health care and banking clients to manage every aspect of staff and vendor information, including registration, screening, credentialing, and monitoring, and to remain in compliance with their internal policies as well as government mandates such as HIPAA, the Stark Law, and the Deficit Reduction Act."]}
{"vibes-media": ["Vibes Media provides mobile applications and marketing services to advertisers and marketing media publishers."]}
{"vibrantmedia": []}
{"vigilant-technologies": ["A global IT services firm specializing exclusively in Oracle Technologies, helping customers envision, plan, implement, and support Oracle-based application, database, and middleware systems across a variety of industries. Its expertise with Oracle technology spans all areas of the Oracle product lineincluding database technology, business intelligence, service oriented architecture (SOA), business process management, J2EE application servers, enterprise application integration, portals and e-business suite applications."]}
{"virtustream": ["Specializes in implementing virtualization and cloud computing for clients that include Becton Dickinson, Blue Cross Blue Shield, and the National Institutes of Health."]}
{"visibletechnologies": []}
{"vivo": ["Places mid- to senior-level IT consultants at companies in industries ranging from financial services to manufacturing."]}
{"vocalocity": ["Ensures higher quality VoIP services through proprietary technology that differentiates it from traditional VoIP providers. With cloud-based connectivity, businesses can work from anywhere while enjoying features that deliver large enterprise visibility and functionality. Vocalocity serves nearly 15,000 customers through a U.S.-based call center in the companys headquarters and provides features at half the traditional costs while never requiring a contract."]}
{"volusion": ["Volusion develops shopping cart software that allows customers to build and manage their own online store or e-commerce capability. Customers can choose from a variety of design templates, or have Volusion create one for them."]}
{"votigo": ["Develops a technology platform that allows businesses to attract and engage their audiences on all social media channels. Its social marketing suite features promotions and marketing applications, Social Conversation Manager, and enhanced insights and analytics. Votigo is a Facebook Preferred Marketing Developer and a Google Engagement Solutions Developer."]}
{"w3i": ["W3i provides digital fee-based and ad-supported marketing services to Internet media companies, direct marketers, e-commerce companies, and others. It combines the traffic of multiple Web properties, including Freeze.com, Ringtone.com, ScreenSaver.com, and Wallpapers.com, reaching 15 million unique users each month."]}
{"wdfa-marketing": ["WDFA Marketing specializes in guerilla, grassroots, and micro-marketing using creative online techniques, demographic mapping software, and street tactics."]}
{"web-advanced": ["Specializes in user-centered Web design, content management, and e-commerce services."]}
{"webpagefx": ["Offers Internet marketing services to mid to large size companies worldwide. Provides customized marketing plans to meet the individual needs of its clients and strives to provide positive results by driving traffic and measuring effectiveness."]}
{"weddingwire": ["A comprehensive platform to help wedding planners and vendors reach prospective clients, schedule online appointments, manage multimedia assets, improve search visibility, manage social media, and network with other local merchants. WeddingWire has branched out into adjacent event areas, including PromWire.com and MitzvahWire.com."]}
{"weddingwire-inc": []}
{"wellmed-medical-management": ["Provides health care services and insurance for seniors in over 30 medical clinics in Texas and Florida"]}
{"whitehat-security": ["WhiteHat Security provides Internet and network security through a subscription-based software-as-a-service (SaaS) platform WhiteHat Sentinel, and by offering hacker-prevention education and classes for its clients."]}
{"willowtree-apps": ["A mobile developer that has launched 70 apps, including for the Valpak and Babycenter (a Johnson & Johnson Company). Its open office environment facilitates collaboration among its employees, all of whom work at its headquarters; none of its work is outsourced overseas."]}
{"winshuttle": ["Winshuttle develops software products that enable business users to work with SAP directly from Excel, Web forms, and other interfaces without any programming."]}
{"worldwide-supply": ["Sells used and refurbished Cisco data and telecommunications networking equipment."]}
{"worthpoint": ["An online resource for collectors that provides market data on art, antiques, and collectibles along with expertise, opinions, and appraisals to help people value, preserve, buy, and sell items. Its core feature, Worthopedia, is a vast database of more than 100 million sales records aggregated from eBay, virtual marketplaces, and auction houses."]}
{"xirrus": ["Xirrus manufactures the patented Wi-Fi Array, a powerful, high-capacity, broad-range Wi-Fi system used to securely deliver data, voice and video services to large user populations, including offices, conference rooms, auditoriums, campuses, warehouses, remote users, and emergency response teams."]}
{"yashi": ["Manages a global advertising network for websites in the online gaming and entertainment industry. Works with game developers and businesses to distribute ads on entertainment and gaming sites that sell advertising space. Brokers the placement of banner ads, pre-roll video ads, in-page ads, Advergames and site skins."]}
{"yext": ["An advertising technology company that helps local businesses monitor their reputation online and stand out in Internet searches."]}
{"yodle": ["Connects local businesses with consumers in major U.S. cities by placing ads in organic and sponsored sections of search engines and local sites and through website design, assessment, and tracking."]}
{"yousendit": ["Allows users to securely transfer electronic files that are too large or too sensitive to e-mail. Its corporate users include Levi's, Ritz Camera, and Reuters."]}
{"zemoga": ["A design and marketing agency that creates engaging interactive experiences and applications. Customers include Sears and Mozilla."]}
{"zenoss": ["Provides management software for physical, virtual, and cloud-based IT infrastructures. Commercial customers include Rackspace, WebMD, LinkedIn, and Deutsche Bank."]}
{"zillow": ["An online marketplace that enables homeowners, buyers, sellers, renters, real estate agents, mortgage professionals, landlords, and property managers to find and share real estate information and make deals. In April 2011, the company acquired online real estate listing creation and distribution platform Postlets, and shortly thereafter filed for an IPO."]}
{"zmags": ["Provides a cloud-based rich-media marketing platform that allows online marketers to create engaging and fluid online presentations with curated digital experiences, including digital catalogs, microsites, and apps, for the Web, tablets, mobile devices, and social channels."]}
{"zoominfo": ["Operates a business information search engine."]}
